name: Code Review Bot

on:
  pull_request:
    branches:
      - main

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v2
        with:
          languages: 'cpp, python'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
